services:
  #  mysql:
  #    image: mysql:8
  #    environment:
  #      MYSQL_ROOT_PASSWORD: Gujjar123!
  #      MYSQL_DATABASE: eventoo
  #    ports:
  #      - "3307:3306"

  real_project_app:
    image: real_project
    ports:
      - "8001:8080"
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/eventoo2
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Gujjar123!
#    depends_on:
#      - mysql