spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

server.forward-headers-strategy=framework

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8080}

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.google.scope=email,profile

#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialecte
#spring.security.user.name = event
#spring.security.user.password = event123
