spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=dgpJJRBTECPuVlyiPzKvIUSmmbmKkxEn

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8080}

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=zainafzaal7890@gmail.com
spring.mail.password=bfujvhhrjenohohd

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.security.oauth2.client.registration.google.client-id=384994618416-12qb90717tpu54prock2bcq4bmsplt4m. apps. googleusercontent. com
spring.security.oauth2.client.registration.google.client-secret=GOCSPX-nWD1STYSSILYVX5ot3901FFZKoV

spring.security.oauth2.client.registration.google.scope=email,profile

#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialecte
#spring.security.user.name = event
#spring.security.user.password = event123
